class X {
	constructor(type, name, cost, speed, range, target, elements, artist, description) {
		this.type = type;
		this.name = name;
		this.cost = cost;
		this.speed = speed;
		this.range = range;
		this.target = target;
		this.elements = elements;
		this.artist = artist;
		this.description = description;
	}

	toJson() {
		return {
			type: this.type,
			name: this.name,
			cost: this.cost,
			speed: this.speed,
			range: this.range?.toString() || '',
			target: Array.isArray(this.target) ? this.target.join(', ') : this.target,
			elements: this.elements.join(', '),
			description: this.description,
		};
	}
}

class Ranges {
	constructor(from, range, land) {
		this.from = from;
		this.range = range;
		this.land = land;
	}

	toString() {
		let res = this.from + "";
		if (this.land) {
			res += " on " + this.land;
		}
		res += ": ";
		if (Array.isArray(this.range)) {
			res += this.range.join(" & ");
		} else {
			res += this.range;
		}
		return res;
	}
}

let Unique = {
	ASpreadOfRampantGreen : "Green",
	BringerOfDreamsAndNightmares : "Nightmares",
	LightngingsSwiftStrike : "Lightning",
	OceansHungryGrasp : "Ocean",
	RiverSurgesInSunlight : "River",
	ShadowsFlickerLikeFlame : "Flame",
	Thunderspeaker : "Thunderspeaker",
	VitalStrengthOfTheEarth : "Earth",
	SharpFangsBehindTheLeaves : "Fangs",
	KeeperOfTheForbiddenWilds : "Wilds",
	SerpentSlumberingBeneathTheIsland : "Serpent",
	HeartOfTheWildfire : "Heart",
	FinderOfPathsUnseen : "Finder",
	FracturedDaysSplitTheSky : "Sky",
	GrinningTricksterStirsUpTrouble : "Trickster",
	LureOfTheDeepWilderness : "Lure",
	ManyMindsMoveAsOne : "Minds",
	ShiftingMemoryOfAges : "Memory",
	ShroudOfSilentMist : "Mist",
	StarlightSeeksItsForm : "Starlight",
	StonesUnyieldingDefiance : "Stone",
	VengeanceAsABurningPlague : "Plague",
	VolcanoLoomingHigh : "Volcano",
	DownpourDrenchesTheWorld : "Downpour",
};

let arr = [
	new X(Unique.LightngingsSwiftStrike, "Shatter Homesteads", 2, 'Slow', new Ranges('SacredSite', 2), 'Land Any',
		['Fire', 'Air'], "Rocky Hammer",
		"1 Fear. Destroy 1 Town."),
	new X(Unique.LightngingsSwiftStrike, "Raging Storm", 3, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Fire', 'Air', 'Water'], "Rocky Hammer",
		"1 Damage to each Invader."),
	new X(Unique.LightngingsSwiftStrike, "Lightning's Boon", 1, 'Fast', null, 'Target Spirit Any',
		['Fire', 'Air'], "Rocky Hammer",
		"Target Spirit may use up to 2 Slow Powers as if they were Fast Powers this turn"),
	new X(Unique.LightngingsSwiftStrike, "Harbingers of the Lightning", 0, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Fire', 'Air'], "Rocky Hammer",
		"Push up to 2 Dahan. 1 Fear if you pushed any Dahan into a land with Town / City"),
	new X(Unique.RiverSurgesInSunlight, "Flash Floods", 2, 'Fast', new Ranges('Presence', 1), 'Land Any',
		['Sun', 'Water'], "Nolan Nasser",
		"1 Damage. If target land is Coastal, +1 Damage."),
	new X(Unique.RiverSurgesInSunlight, "Wash Away", 1, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Water', 'Earth'], "Nolan Nasser",
		"Push up to 3 Explorer / Town"),
	new X(Unique.RiverSurgesInSunlight, "Boon of Vigor", 0, 'Fast', null, 'Target Spirit Any',
		['Sun', 'Water', 'Plant'], "Nolan Nasser",
		"If you target yourself, gain 1 Energy. If you target another Spirit, they gain 1 Energy per Power Card they played this turn."),
	new X(Unique.RiverSurgesInSunlight, "River's Bounty", 0, 'Slow', new Ranges('Presence', 0), 'Land Any',
		['Sun', 'Water', 'Animal'], "Nolan Nasser",
		"Gather up to 2 Dahan. If there are now at least 2 Dahan, add 1 Dahan and gain 1 Energy."),
	new X(Unique.ShadowsFlickerLikeFlame, "Concealing Shadows", 0, 'Fast', new Ranges('Presence', 0), 'Land Any',
		['Moon', 'Air'], "Nolan Nasser",
		"1 Fear. Dahan take no damage from Ravaging Invaders this turn."),
	new X(Unique.ShadowsFlickerLikeFlame, "Favors Called Due", 1, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Moon', 'Air', 'Animal'], "Nolan Nasser",
		"Gather up to 4 Dahan. If Invaders are present and Dahan now outnumber them, 3 Fear."),
	new X(Unique.ShadowsFlickerLikeFlame, "Mantle of Dread", 1, 'Slow', null, 'Target Spirit Any',
		['Moon', 'Fire', 'Air'], "Nolan Nasser",
		"2 Fear. Target Spirit may Push 1 Explorer and 1 Town from a land where it has Presence."),
	new X(Unique.ShadowsFlickerLikeFlame, "Crops Wither and Fade", 1, 'Slow', new Ranges('Presence', 0), 'Land Any',
		['Moon', 'Fire', 'Plant'], "Nolan Nasser",
		"2 Fear. Replace 1 Town with 1 Explorer. -or- Replace 1 City with 1 Town."),
	new X(Unique.VitalStrengthOfTheEarth, "Guard the Healing Land", 3, 'Fast', new Ranges('SacredSite', 1), 'Land Any',
		['Water', 'Earth', 'Plant'], "Sydni Kruger",
		"Remove 1 Blight. Defend 4."),
	new X(Unique.VitalStrengthOfTheEarth, "A Year of Perfect Stillness", 3, 'Fast', new Ranges('Presence', 1), 'Land Any',
		['Sun', 'Earth'], "Sydni Kruger",
		"Invaders skip all Actions in target land this turn."),
	new X(Unique.VitalStrengthOfTheEarth, "Rituals of Destruction", 3, 'Slow', new Ranges('SacredSite', 1), 'Dahan',
		['Sun', 'Moon', 'Fire', 'Earth', 'Plant'], "Sydni Kruger",
		"2 Damage. If target land has at least 3 Dahan, +3 Damage and 2 Fear."),
	new X(Unique.VitalStrengthOfTheEarth, "Draw of the Fruitful Earth", 1, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Earth', 'Plant', 'Animal'], "Sydni Kruger",
		"Gather up to 2 Explorer. Gather up to 2 Dahan."),
	new X(Unique.Thunderspeaker, "Manifestation of Power and Glory", 3, 'Slow', new Ranges('Presence', 0), 'Dahan',
		['Sun', 'Fire', 'Air'], "Loic Belliau",
		"1 Fear. Each Dahan deals damage equal to the number of your Presence in target land."),
	new X(Unique.Thunderspeaker, "Words of Warning", 1, 'Fast', new Ranges('Presence', 1), 'Dahan',
		['Sun', 'Air', 'Animal'], "Loic Belliau",
		"Defend 3. During Ravage, Dahan in target land deal damage simultaneously with Invaders."),
	new X(Unique.Thunderspeaker, "Sudden Ambush", 2, 'Fast', new Ranges('Presence', 1), 'Land Any',
		['Fire', 'Air', 'Animal'], "Loic Belliau",
		"You may Gather 1 Dahan. Each Dahan destroys 1 Explorer."),
	new X(Unique.Thunderspeaker, "Voice of Thunder", 0, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Sun', 'Air'], "Loic Belliau",
		"Push up to 4 Dahan. -or- If Invaders are Present, 2 Fear."),
	new X(Unique.OceansHungryGrasp, "Call of the Deeps", 0, 'Fast', new Ranges('Presence', 0), 'Coastal',
		['Moon', 'Air', 'Water'], "Joshua Wright",
		"Gather 1 Explorer. If target land is the Ocean, you may Gather another Explorer."),
	new X(Unique.OceansHungryGrasp, "Grasping Tide", 1, 'Fast', new Ranges('Presence', 1), 'Coastal',
		['Moon', 'Water'], "Joshua Wright",
		"2 Fear. Defend 4."),
	new X(Unique.OceansHungryGrasp, "Swallow the Land-Dwellers", 0, 'Slow', new Ranges('Presence', 0), 'Coastal',
		['Water', 'Earth'], "Joshua Wright",
		"Drown 1 Explorer, 1 Town, and 1 Dahan."),
	new X(Unique.OceansHungryGrasp, "Tidal Boon", 1, 'Slow', null, 'Target Spirit Another',
		['Moon', 'Water', 'Earth'], "Joshua Wright",
		"Target Spirit gains 2 Energy and may Push 1 Town and up to 2 Dahan from one of their lands. If Dahan are pushed to your ocean, you may move them to any Coastal land instead of Drowning them."),
	new X(Unique.BringerOfDreamsAndNightmares, "Predatory Nightmares", 2, 'Slow', new Ranges('SacredSite', 1), 'Invaders',
		['Moon', 'Fire', 'Earth', 'Animal'], "Shane Tyree",
		"2 Damage. Push up to 2 Dahan. (When your powers would destroy Invaders, instead they generate Fear and/or Push those Invaders.)"),
	new X(Unique.BringerOfDreamsAndNightmares, "Dread Apparitions", 2, 'Fast', new Ranges('Presence', 1), 'Invaders',
		['Moon', 'Air'], "Shane Tyree",
		"When Powers generate Fear in target land, Defend 1 per Fear. 1 Fear. (Fear from To Dream a Thousand Deaths counts. Fear from destroying Town / City does not.)"),
	new X(Unique.BringerOfDreamsAndNightmares, "Call on Midnight's Dream", 0, 'Fast', new Ranges('Presence', 0), 'Land Any',
		['Moon', 'Animal'], "Shane Tyree",
		"If target land has Dahan, gain a Major Power. If you Forget this Power, gain Energy equal to Dahan and you may play the Major Power immediately, paying its cost. -or- If Invaders are present, 2 Fear."),
	new X(Unique.BringerOfDreamsAndNightmares, "Dreams of the Dahan", 0, 'Fast', new Ranges('Presence', 2), 'Land Any',
		['Moon', 'Air'], "Shane Tyree",
		"Gather up to 2 Dahan. -or- If target land has Town / City, 1 Fear for each Dahan, to a maximum of 3 Fear."),
	new X(Unique.ASpreadOfRampantGreen, "Overgrow in a Night", 2, 'Fast', new Ranges('Presence', 1), 'Land Any',
		['Moon', 'Plant'], "Jorge Ramos",
		"Add 1 Presence. -or- If target land has your Presence and Invaders, 3 Fear."),
	new X(Unique.ASpreadOfRampantGreen, "Gift of Proliferation", 1, 'Fast', null, 'Target Spirit Another',
		['Moon', 'Plant'], "Jorge Ramos",
		"Target Spirit adds 1 Presence up to 1 Range from their Presence."),
	new X(Unique.ASpreadOfRampantGreen, "Fields Choked with Growth", 0, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Sun', 'Water', 'Plant'], "Jorge Ramos",
		"Push 1 Town. -or- Push 3 Dahan"),
	new X(Unique.ASpreadOfRampantGreen, "Stem the Flow of Fresh Water", 0, 'Slow', new Ranges('SacredSite', 1), 'Land Any',
		['Water', 'Plant'], "Jorge Ramos",
		"1 Damage to 1 Town / City. If target land is Mountain / Sands, instead, 1 Damage to each Town / City."),

	// Colored Corners
	// green corner
	new X('Minor', "Savage Mawbeasts", 0, 'Slow', new Ranges('SacredSite', 1), 'Land Any',
		['Fire', 'Animal'], "Cari Corene",
		"If target land is Jungle / Wetland, 1 Fear and 1 Damage. -If you have- 3 Animal: 1 Damage."),
	new X('Minor', "Voracious Growth", 1, 'Slow', new Ranges('SacredSite', 1), ['Jungle', 'Wetland'],
		['Water', 'Plant'], "Cari Corene",
		"2 Damage. -or- Remove 1 Blight."),
	new X('Minor', "Rouse the Trees and Stones", 1, 'Slow', new Ranges('SacredSite', 1), 'No Blight',
		['Fire', 'Earth', 'Plant'], "Jorge Ramos",
		"2 Damage. Push 1 Explorer."),
	// blue corner
	new X('Minor', "Encompassing Ward", 1, 'Fast', null, 'Target Spirit Any',
		['Sun', 'Water', 'Earth'], "Jorge Ramos",
		"Defend 2 in every land where target Spirit has Presence."),
	new X('Minor', "Song of Sanctity", 1, 'Slow', new Ranges('Presence', 1), ['Mountain', 'Jungle'],
		['Sun', 'Water', 'Plant'], "Nolan Nasser",
		"If target land has 1 Explorer, Push all Explorer. Otherwise, remove 1 Blight."),
	new X('Minor', "Uncanny Melting", 1, 'Slow', new Ranges('SacredSite', 1), 'Land Any',
		['Sun', 'Moon', 'Water'], "Joshua Wright",
		"If Invaders are present, 1 Fear. If target land is Sands / Wetland, remove 1 Blight"),
	// red corner
	new X('Minor', "Shadows of the Burning Forest", 0, 'Slow', new Ranges('Presence', 0), 'Invaders',
		['Moon', 'Fire', 'Plant'], "Nolan Nasser",
		"2 Fear. If target land is Mountain / Jungle, Push 1 Explorer and 1 Town."),

	// Minors inside color cornered block
	new X('Minor', "Steam Vents", 1, 'Fast', new Ranges('Presence', 0), 'Land Any',
		['Fire', 'Air', 'Water', 'Earth'], "Joshua Wright",
		"Destroy 1 Explorer. -If you have- 3 Earth: You may instead destroy 1 Town."),
	new X('Minor', "Veil the Night's Hunt", 1, 'Fast', new Ranges('Presence', 2), 'Dahan',
		['Moon', 'Air', 'Animal'], "Loic Belliau",
		"Each Dahan deals 1 Damage to a different Invader. -or- Push up to 3 Dahan."),
	new X('Minor', "Elemental Boon", 1, 'Fast', null, 'Target Spirit Any',
		[], "Moro Rogers",
		"'Target Spirit gains 3 different of their choice. If you target another Spirit, you also gain the chosen '"),

	// Second Badge
	// Minors
	new X('Minor', "Devouring Ants", 1, 'Slow', new Ranges('SacredSite', 1), 'Land Any',
		['Sun', 'Earth', 'Animal'], "Nolan Nasser",
		"1 Fear. 1 Damage. Destroy 1 Dahan. If target land is Jungle / Sands, +1 Damage."),
	new X('Minor', "Dark and Tangled Woods", 1, 'Fast', new Ranges('Presence', 1), 'Land Any',
		['Moon', 'Earth', 'Plant'], "Nolan Nasser",
		"2 Fear. If target land is Mountain / Jungle, Defend 3."),
	new X('Minor', "Sap the Strength of Multitudes", 0, 'Fast', new Ranges('Presence', 0), 'Land Any',
		['Water', 'Animal'], "Loic Belliau",
		"Defend 5. -If you have- 1 Air: Increase this Power's Range by 1"),
	new X('Minor', "Drift down into Slumber", 0, 'Fast', new Ranges('Presence', 2), 'Land Any',
		['Air', 'Earth', 'Plant'], "Lucas Durham",
		"Defend 1. If target land is Jungle / Sands, instead, Defend 4."),
	new X('Minor', "Land of Haunts and Embers", 0, 'Fast', new Ranges('Presence', 2), 'Land Any',
		['Moon', 'Fire', 'Air'], "Jorge Ramos",
		"2 Fear. Push up to 2 Explorer / Town. If target land has Blight, +2 Fear. Push up to 2 more Explorer / Town. Add 1 Blight."),
	new X('Minor', "Nature's Resilience", 1, 'Fast', new Ranges('SacredSite', 1), 'Land Any',
		['Earth', 'Plant', 'Animal'], "Joshua Wright",
		"Defend 6. -If you have- 2 Water: You may instead remove 1 Blight."),
	new X('Minor', "Visions of Fiery Doom", 1, 'Fast', new Ranges('Presence', 0), 'Land Any',
		['Moon', 'Fire'], "Lucas Durham",
		"1 Fear. Push 1 Explorer / Town. -If you have- 2 Fire: +1 Fear."),
	new X('Minor', "Pull Beneath the Hungry Earth", 1, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Moon', 'Water', 'Earth'], "Nolan Nasser",
		"If target land has your Presence, 1 Fear and 1 Damage. If target land is Sands / Wetland, 1 Damage."),
	new X('Minor', "Call of the Dahan Ways", 1, 'Slow', new Ranges('Presence', 1), 'Dahan',
		['Moon', 'Water', 'Animal'], "Loic Belliau",
		"Replace 1 Explorer with 1 Dahan. -If you have- 2 Moon: You may instead replace 1 Town with 1 Dahan."),
	new X('Minor', "Call to Bloodshed", 1, 'Slow', new Ranges('Presence', 1), 'Dahan',
		['Sun', 'Fire', 'Animal'], "Jorge Ramos",
		"1 Damage per Dahan. -or- Gather up to 3 Dahan."),
	new X('Minor', "Call to Isolation", 0, 'Fast', new Ranges('Presence', 1), 'Dahan',
		['Sun', 'Air', 'Animal'], "Graham Stermberg",
		"Push 1 Explorer / Town per Dahan. -or- Push 1 Dahan."),
	new X('Minor', "Call to Migrate", 1, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Fire', 'Air', 'Animal'], "Graham Stermberg",
		"Gather up to 3 Dahan. Push up to 3 Dahan."),
	new X('Minor', "Call to Tend", 1, 'Slow', new Ranges('Presence', 1), 'Dahan',
		['Water', 'Plant', 'Animal'], "Loic Belliau",
		"Remove 1 Blight. -or- Push up to 3 Dahan."),
	new X('Minor', "Quicken the Earth's Struggles", 1, 'Fast', new Ranges('SacredSite', 0), 'Land Any',
		['Moon', 'Fire', 'Earth', 'Animal'], "Lucas Durham",
		"1 Damage to each Town / City. -or- Defend 10."),
	new X('Minor', "Delusions of Danger", 1, 'Fast', new Ranges('Presence', 1), 'Land Any',
		['Sun', 'Moon', 'Air'], "Moro Rogers",
		"Push 1 Explorer. -or- 2 Fear."),
	new X('Minor', "Drought", 1, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Sun', 'Fire', 'Earth'], "Nolan Nasser",
		"Destroy 3 Town. 1 Damage to each Town / City. Add 1 Blight. -If you have- 3 Sun: Destroy 1 City."),
	new X('Minor', "Gift of Constancy", 0, 'Fast', null, 'Target Spirit Any',
		['Sun', 'Earth'], "Moro Rogers",
		"Target Spirit gains 2 Energy. At end of turn, target Spirit may Reclaim 1 Power Card instead of discarding it. If you target another Spirit, you may also Reclaim 1 Power Card instead of discarding it."),
	new X('Minor', "Enticing Splendor", 0, 'Fast', new Ranges('Presence', 0), 'No Blight',
		['Sun', 'Air', 'Plant'], "Joshua Wright",
		"Gather 1 Explorer / Town. -or- Gather up to 2 Dahan."),
	new X('Minor', "Entrancing Apparitions", 1, 'Fast', new Ranges('Presence', 1), 'Land Any',
		['Moon', 'Air', 'Water'], "Moro Rogers",
		"Defend 2. If no Invaders are present, gather up to 2 Explorer."),
	new X('Minor', "Gift of Living Energy", 0, 'Fast', null, 'Target Spirit Any',
		['Sun', 'Fire', 'Plant'], "Nolan Nasser",
		"Target Spirit gains 1 Energy, +1 Energy if target Spirit is not yourself. If you have at least 2 sacred site, target Spirit gains +1 Energy."),
	new X('Minor', "Gift of Power", 0, 'Slow', null, 'Target Spirit Any',
		['Moon', 'Water', 'Earth', 'Plant'], "Joshua Wright",
		"Gain a Minor Power Card."),
	new X('Minor', "Gnawing Rootbiters", 0, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Earth', 'Animal'], "Moro Rogers",
		"Push up to 2 Town."),
	new X('Minor', "Lure of the Unknown", 0, 'Fast', new Ranges('Presence', 2), 'NoInvaders',
		['Moon', 'Fire', 'Air', 'Plant'], "Lucas Durham",
		"Gather 1 Explorer / Town"),
	new X('Minor', "Purifying Flame", 1, 'Slow', new Ranges('SacredSite', 1), 'Land Any',
		['Sun', 'Fire', 'Air', 'Plant'], "Jorge Ramos",
		"1 Damage per Blight. If target land is Mountain / Sands, you may instead remove 1 Blight."),
	new X('Minor', "Rain of Blood", 0, 'Slow', new Ranges('SacredSite', 1), 'Invaders',
		['Air', 'Water', 'Animal'], "Kat Birmelin",
		"2 Fear. If target land has at least 2 Town / City, +1 Fear."),
	new X('Minor', "Reaching Grasp", 0, 'Fast', null, 'Target Spirit Any',
		['Sun', 'Air', 'Water'], "Nolan Nasser",
		"Target Spirit gets +2 Range with all their Powers."),
	// Majors
	new X('Major', "Accelerated Rot", 4, 'Slow', new Ranges('Presence', 2), ['Jungle', 'Wetland'],
		['Sun', 'Water', 'Plant'], "Graham Stermberg",
		"2 Fear. 4 Damage. -If you have- 3 Sun, 2 Water, 3 Plant: +5 Damage. Remove 1 Blight."),
	new X('Major', "Cleansing Floods", 5, 'Slow', new Ranges('Presence', 1, ['Wetland']), 'Land Any',
		['Sun', 'Water'], "Nolan Nasser",
		"4 Damage. Remove 1 Blight. -If you have- 4 Water: +10 Damage."),
	new X('Major', "Pillar of Living Flame", 5, 'Slow', new Ranges('SacredSite', 2), 'Land Any',
		['Fire'], "Jorge Ramos",
		"3 Fear. 5 Damage. If target land is Jungle / Wetland, add 1 Blight. -If you have- 4 Fire: +2 Fear and +5 Damage."),
	new X('Major', "Poisoned Land", 3, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Earth', 'Plant', 'Animal'], "Nolan Nasser",
		"1 Fear. 7 Damage. Add 1 Blight and destroy all Dahan. -If you have- 3 Earth, 2 Plant, 2 Animal: For each Blight then present, +1 Fear and +4 Damage."),
	new X('Major', "Terrifying Nightmares", 4, 'Fast', new Ranges('Presence', 2), 'Land Any',
		['Moon', 'Air'], "Loic Belliau",
		"2 Fear. Push up to 4 Explorer / Town. -If you have- 4 Moon: +4 Fear."),
	new X('Major', "The Trees and Stones Speak of War", 2, 'Fast', new Ranges('Presence', 1), 'Dahan',
		['Sun', 'Earth', 'Plant'], "Graham Stermberg",
		"For each Dahan in target land, 1 Damage and Defend 2. -If you have- 2 Sun, 2 Earth, 2 Plant: You may Push up to 2 Dahan, moving each's Defend with them."),
	new X('Major', "Entwined Power", 2, 'Fast', null, 'Target Spirit Another',
		['Moon', 'Water', 'Plant'], "Joshua Wright",
		"You and target Spirit may use each other's Presence to target Powers. Target Spirit gains a Power Card. You gain one of the power Cards they did not keep. -If you have- 2 Water, 4 Plant: You and target Spirit each gain 3 Energy and may gift the other 1 Power from hand."),
	new X('Major', "Paralyzing Fright", 4, 'Fast', new Ranges('SacredSite', 1), 'Land Any',
		['Air', 'Earth'], "Joshua Wright",
		"4 Fear. Invaders skip all Actions in target land this turn. -If you have- 2 Air, 3 Earth: +4 Fear."),
	new X('Major', "Powerstorm", 3, 'Fast', null, 'Target Spirit Any',
		['Sun', 'Fire', 'Air'], "Nolan Nasser",
		"Target Spirit gains 3 Energy. Once this turn, target may Repeat a Power Card by paying its cost again. -If you have- 2 Sun, 2 Fire, 3 Air: Target may Repeat up to 2 more Power Cards by paying their costs."),
	new X('Major', "Talons of Lightning", 6, 'Fast', new Ranges('Presence', 1), ['Mountain', 'Wetland'],
		['Fire', 'Air'], "Nolan Nasser",
		"3 Fear. 5 Damage. -If you have- 3 Fire, 3 Air: Destroy 1 Town in each adjacent land. Increase this power's Range to 3 Range."),
	new X('Major', "The Jungle Hungers", 3, 'Slow', new Ranges('Presence', 1, ['Jungle']), 'Land Any',
		['Moon', 'Plant'], "Joshua Wright",
		"Destroy all Explorer and all Town. Destroy all Dahan. -If you have- 2 Moon, 3 Plant: Destroy 1 City. Do not destroy any Dahan."),
	new X('Major', "The Land Thrashes in Furious Pain", 4, 'Slow', new Ranges('Presence', 2), 'Blight',
		['Moon', 'Fire', 'Earth'], "Nolan Nasser",
		"2 Damage per Blight in target land. +1 Damage per Blight in adjacent lands. -If you have- 3 Moon, 3 Earth: Repeat on an adjacent land."),
	new X('Major', "Tsunami", 6, 'Slow', new Ranges('SacredSite', 2), 'Coastal',
		['Water', 'Earth'], "Jason Behnke",
		"2 Fear. 8 Damage. Destroy 2 Dahan. -If you have- 3 Water, 2 Earth: In each otdher Coastal land on the same board: 1 Fear, 4 Damage, and Destroy 1 Dahan."),
	new X('Major', "Vigor of the Breaking Dawn", 3, 'Fast', new Ranges('Presence', 2), 'Dahan',
		['Sun', 'Animal'], "Loic Belliau",
		"2 Damage per Dahan in target land. -If you have- 3 Sun, 2 Animal: You may Push up to 2 Dahan. In lands you Pushed Dahan to, 2 Damage per Dahan."),
	new X('Major', "Vengeance of the Dead", 3, 'Fast', new Ranges('Presence', 3), 'Land Any',
		['Moon', 'Fire', 'Animal'], "Kat Birmelin",
		"3 Fear. After each effect that destroys Town / City / Dahan in target land, 1 Damage per Town / City / Dahan destroyed. -If you have- 3 Animal: Damage from this Power may be dealt into adjacent lands."),
	new X('Major', "Wrap in Wings of Sunlight", 3, 'Fast', new Ranges('Presence', 0), 'Land Any',
		['Sun', 'Air', 'Animal'], "Loic Belliau",
		"Move up to 5 Dahan from target land to any land. Defend 5 in that land. -If you have- 2 Sun, 2 Air, 2 Animal: First, Gather up to 3 Dahan."),
	new X('Major', "Blazing Renewal", 5, 'Fast', null, 'Target Spirit Any',
		['Fire', 'Earth', 'Plant'], "Nolan Nasser",
		"Target Spirit adds 2 of their destroyed Presence into a single land, up to 2 Range from your Presence. If any Presence was added, 2 damage to each Town / City in that land. -If you have- 3 Fire, 3 Earth, 2 Plant: 4 Damage in that land."),
	new X('Major', "Winds of Rust and Atrophy", 3, 'Fast', new Ranges('SacredSite', 3), 'Land Any',
		['Air', 'Water', 'Animal'], "Joshua Wright",
		"1 Fear and Defend 6. Replace 1 City with 1 Town or 1 Town with 1 Explorer. -If you have- 3 Air, 3 Water, 2 Animal: Repeat this Power."),
	new X('Major', "Indomitable Claim", 4, 'Fast', new Ranges('Presence', 1), 'Land Any',
		['Sun', 'Earth'], "Jorge Ramos",
		"Add 1 Presence in target land even if you normally could not due to land type. Defend 20. -If you have- 2 Sun, 3 Earth: 3 Fear if Invaders are present. Invaders skip all Actions in target land this turn."),
	new X('Major', "Mists of Oblivion", 4, 'Slow', new Ranges('Presence', 3), 'Land Any',
		['Moon', 'Air', 'Water'], "Nolan Nasser",
		"1 Fear per Town / City this Power destroys (to a maximum of 4). 1 Damage to each Invader. -If you have- 2 Moon, 3 Air, 2 Water: 3 Damage."),
	new X('Major', "Infinite Vitality", 3, 'Fast', new Ranges('SacredSite', 1), 'Land Any',
		['Earth', 'Plant', 'Animal'], "Joshua Wright",
		"Dahan have +4 Health while in target land. Whenever Blight would be added to target land, instead leave it on the card. -If you have- 4 Earth: Dahan ignore Damage and Destruction effects. Remove 1 Blight from target or adjacent land."),
	new X('Major', "Dissolve the Bonds of Kinship", 4, 'Slow', new Ranges('Presence', 1), 'Land Any',
		['Fire', 'Water', 'Animal'], "Jorge Ramos",
		"Replace 1 City with 2 Explorer. Replace 1 Town with 1 Explorer. Replace 1 Dahan with 1 Explorer. Push all Explorer from target land to as many different lands as possible. -If you have- 2 Fire, 2 Water, 3 Animal: Before Pushing, Explorer and Town / City do Damage to each other."),
];

let s = JSON.stringify(arr.map(a => a.toJson()));
console.log(s);
